ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=stable
ARG HTTP_PROXY
ARG HTTPS_PROXY

# Stage 1: Build dependencies
FROM ${sourceimage}:${sourcetag} AS builder

USER root
ENV HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY}
RUN pip install --upgrade pip

COPY --chown=1000:1000 tests/requirements.txt /freqtrade/

USER ftuser
RUN --mount=type=cache,target=/home/ftuser/.cache/pip \
    pip install --user --no-build-isolation --no-cache-dir -r /freqtrade/requirements.txt

USER root
# Fix ownership of user install directory
RUN chown -R 1000:1000 /home/ftuser/.local

# Stage 2: Final image
FROM ${sourceimage}:${sourcetag}

USER root

COPY --from=builder /home/ftuser/.local /home/ftuser/.local
COPY --chown=1000:1000 tests/requirements.txt /freqtrade/

USER ftuser

ENV PATH=/home/ftuser/.local/bin:$PATH
